<?php include_once("php/connect.php"); ?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Ria's</title>
  <link rel="stylesheet" href="css/main.css">
  <link rel="stylesheet" href="css/nav-foot.css">
  <link href='https://fonts.googleapis.com/css?family=Josefin Sans' rel='stylesheet'>
</head>

<body>
  <!-- Navbar -->
  <?php include_once("includes/navbar.php"); ?>

  <!-- Main -->
  <main>
   usollicitudin tincidunt vehicula. Phasellus eu elementum lectus. Suspendisse ut elit tempus, fermentum mi vel, sodales nisi. Nullam ac eleifend ex. In ac purus nec velit tincidunt iaculis. Nulla pretium ornare sapien. Praesent dignissim interdum eros, a tincidunt sem vestibulum a. Fusce posuere urna a ligula semper, ut vehicula diam fermentum.
    Maecenas non lacus tempus, tristique lorem vel, venenatis libero. Fusce id auctor ipsum, in accumsan nisl. Maecenas at mollis risus, ut pulvinar quam. Nam ultrices sodales sagittis. Suspendisse potenti. Nulla convallis aliquet tellus at consequat. Etiam convallis et lacus efficitur tincidunt. Praesent at mi ut sem convallis maximus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed convallis condimentum ipsum tempor mollis. Fusce non malesuada orci.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et sem congue, iaculis ante et, facilisis enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam quis nisi at est viverra sagittis. Nullam eget lacinia velit. Mauris sagittis urna ut leo sagittis commodo. Donec pellentesque porta urna sed fermentum. Curabitur pretium nisi metus, sit amet porttitor elit porttitor ac. In hac habitasse platea dictumst. Etiam tempor, sem quis placerat dapibus, nisl mi sodales sem, tempus ullamcorper eros ante nec odio.
    Morbi a convallis ligula. Nunc lacinia, felis at mattis placerat, est enim tincidunt nibh, nec tempor sem diam quis odio. Curabitur mattis, urna non tincidunt bibendum, eros justo iaculis sem, et fermentum metus sapien vel erat. Suspendisse dignissim neque eu leo suscipit accumsan. Praesent consectetur maximus fermentum. Nullam sollicitudin, nunc consectetur fermentum porttitor, turpis leo ullamcorper leo, a volutpat erat mi vel nibh. Proin a massa ac sapien facilisis aliquet. Pellentesque sodales nisl sit amet ultrices scelerisque. Mauris a mauris est. Aenean at consectetur lorem. Proin interdum rutrum erat vel imperdiet. Maecenas ullamcorper scelerisque volutpat. Fusce tincidunt tempus bibendum.
    Morbi mollis neque lorem, sit amet lacinia odio lacinia ut. Sed commodo porttitor turpis a pulvinar. Maecenas neque ipsum, pellentesque nec tincidunt et, malesuada sed enim. Vivamus pulvinar consequat ante, vel efficitur diam placerat et. Mauris vel leo a quam egestas tempor. Etiam a libero ipsum. Aenean sagittis ante in mi ornare, porta tincidunt libero sollicitudin. Proin mollis laoreet dolor, consectetur convallis massa blandit blandit. Etiam facilisis euismod tellus, ac pharetra lorem elementum vitae. In congue nunc vitae aliquet sollicitudin. Quisque rhoncus urna maximus tincidunt fringilla.
    Phasellus sollicitudin tincidunt vehicula. Phasellus eu elementum lectus. Suspendisse ut elit tempus, fermentum mi vel, sodales nisi. Nullam ac eleifend ex. In ac purus nec velit tincidunt iaculis. Nulla pretium ornare sapien. Praesent dignissim interdum eros, a tincidunt sem vestibulum a. Fusce posuere urna a ligula semper, ut vehicula diam fermentum.
    Maecenas non lacus tempus, tristique lorem vel, venenatis libero. Fusce id auctor ipsum, in accumsan nisl. Maecenas at mollis risus, ut pulvinar quam. Nam ultrices sodales sagittis. Suspendisse potenti. Nulla convallis aliquet tellus at consequat. Etiam convallis et lacus efficitur tincidunt. Praesent at mi ut sem convallis maximus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed convallis condimentum ipsum tempor mollis. Fusce non malesuada orci.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et sem congue, iaculis ante et, facilisis enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam quis nisi at est viverra sagittis. Nullam eget lacinia velit. Mauris sagittis urna ut leo sagittis commodo. Donec pellentesque porta urna sed fermentum. Curabitur pretium nisi metus, sit amet porttitor elit porttitor ac. In hac habitasse platea dictumst. Etiam tempor, sem quis placerat dapibus, nisl mi sodales sem, tempus ullamcorper eros ante nec odio.
    Morbi a convallis ligula. Nunc lacinia, felis at mattis placerat, est enim tincidunt nibh, nec tempor sem diam quis odio. Curabitur mattis, urna non tincidunt bibendum, eros justo iaculis sem, et fermentum metus sapien vel erat. Suspendisse dignissim neque eu leo suscipit accumsan. Praesent consectetur maximus fermentum. Nullam sollicitudin, nunc consectetur fermentum porttitor, turpis leo ullamcorper leo, a volutpat erat mi vel nibh. Proin a massa ac sapien facilisis aliquet. Pellentesque sodales nisl sit amet ultrices scelerisque. Mauris a mauris est. Aenean at consectetur lorem. Proin interdum rutrum erat vel imperdiet. Maecenas ullamcorper scelerisque volutpat. Fusce tincidunt tempus bibendum.
    Morbi mollis neque lorem, sit amet lacinia odio lacinia ut. Sed commodo porttitor turpis a pulvinar. Maecenas neque ipsum, pellentesque nec tincidunt et, malesuada sed enim. Vivamus pulvinar consequat ante, vel efficitur diam placerat et. Mauris vel leo a quam egestas tempor. Etiam a libero ipsum. Aenean sagittis ante in mi ornare, porta tincidunt libero sollicitudin. Proin mollis laoreet dolor, consectetur convallis massa blandit blandit. Etiam facilisis euismod tellus, ac pharetra lorem elementum vitae. In congue nunc vitae aliquet sollicitudin. Quisque rhoncus urna maximus tincidunt fringilla.
    Phasellus sollicitudin tincidunt vehicula. Phasellus eu elementum lectus. Suspendisse ut elit tempus, fermentum mi vel, sodales nisi. Nullam ac eleifend ex. In ac purus nec velit tincidunt iaculis. Nulla pretium ornare sapien. Praesent dignissim interdum eros, a tincidunt sem vestibulum a. Fusce posuere urna a ligula semper, ut vehicula diam fermentum.
    Maecenas non lacus tempus, tristique lorem vel, venenatis libero. Fusce id auctor ipsum, in accumsan nisl. Maecenas at mollis risus, ut pulvinar quam. Nam ultrices sodales sagittis. Suspendisse potenti. Nulla convallis aliquet tellus at consequat. Etiam convallis et lacus efficitur tincidunt. Praesent at mi ut sem convallis maximus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed convallis condimentum ipsum tempor mollis. Fusce non malesuada orci.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et sem congue, iaculis ante et, facilisis enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam quis nisi at est viverra sagittis. Nullam eget lacinia velit. Mauris sagittis urna ut leo sagittis commodo. Donec pellentesque porta urna sed fermentum. Curabitur pretium nisi metus, sit amet porttitor elit porttitor ac. In hac habitasse platea dictumst. Etiam tempor, sem quis placerat dapibus, nisl mi sodales sem, tempus ullamcorper eros ante nec odio.
    Morbi a convallis ligula. Nunc lacinia, felis at mattis placerat, est enim tincidunt nibh, nec tempor sem diam quis odio. Curabitur mattis, urna non tincidunt bibendum, eros justo iaculis sem, et fermentum metus sapien vel erat. Suspendisse dignissim neque eu leo suscipit accumsan. Praesent consectetur maximus fermentum. Nullam sollicitudin, nunc consectetur fermentum porttitor, turpis leo ullamcorper leo, a volutpat erat mi vel nibh. Proin a massa ac sapien facilisis aliquet. Pellentesque sodales nisl sit amet ultrices scelerisque. Mauris a mauris est. Aenean at consectetur lorem. Proin interdum rutrum erat vel imperdiet. Maecenas ullamcorper scelerisque volutpat. Fusce tincidunt tempus bibendum.
    Morbi mollis neque lorem, sit amet lacinia odio lacinia ut. Sed commodo porttitor turpis a pulvinar. Maecenas neque ipsum, pellentesque nec tincidunt et, malesuada sed enim. Vivamus pulvinar consequat ante, vel efficitur diam placerat et. Mauris vel leo a quam egestas tempor. Etiam a libero ipsum. Aenean sagittis ante in mi ornare, porta tincidunt libero sollicitudin. Proin mollis laoreet dolor, consectetur convallis massa blandit blandit. Etiam facilisis euismod tellus, ac pharetra lorem elementum vitae. In congue nunc vitae aliquet sollicitudin. Quisque rhoncus urna maximus tincidunt fringilla.
    Phasellus sollicitudin tincidunt vehicula. Phasellus eu elementum lectus. Suspendisse ut elit tempus, fermentum mi vel, sodales nisi. Nullam ac eleifend ex. In ac purus nec velit tincidunt iaculis. Nulla pretium ornare sapien. Praesent dignissim interdum eros, a tincidunt sem vestibulum a. Fusce posuere urna a ligula semper, ut vehicula diam fermentum.
    Maecenas non lacus tempus, tristique lorem vel, venenatis libero. Fusce id auctor ipsum, in accumsan nisl. Maecenas at mollis risus, ut pulvinar quam. Nam ultrices sodales sagittis. Suspendisse potenti. Nulla convallis aliquet tellus at consequat. Etiam convallis et lacus efficitur tincidunt. Praesent at mi ut sem convallis maximus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed convallis condimentum ipsum tempor mollis. Fusce non malesuada orci.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et sem congue, iaculis ante et, facilisis enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam quis nisi at est viverra sagittis. Nullam eget lacinia velit. Mauris sagittis urna ut leo sagittis commodo. Donec pellentesque porta urna sed fermentum. Curabitur pretium nisi metus, sit amet porttitor elit porttitor ac. In hac habitasse platea dictumst. Etiam tempor, sem quis placerat dapibus, nisl mi sodales sem, tempus ullamcorper eros ante nec odio.
    Morbi a convallis ligula. Nunc lacinia, felis at mattis placerat, est enim tincidunt nibh, nec tempor sem diam quis odio. Curabitur mattis, urna non tincidunt bibendum, eros justo iaculis sem, et fermentum metus sapien vel erat. Suspendisse dignissim neque eu leo suscipit accumsan. Praesent consectetur maximus fermentum. Nullam sollicitudin, nunc consectetur fermentum porttitor, turpis leo ullamcorper leo, a volutpat erat mi vel nibh. Proin a massa ac sapien facilisis aliquet. Pellentesque sodales nisl sit amet ultrices scelerisque. Mauris a mauris est. Aenean at consectetur lorem. Proin interdum rutrum erat vel imperdiet. Maecenas ullamcorper scelerisque volutpat. Fusce tincidunt tempus bibendum.
    Morbi mollis neque lorem, sit amet lacinia odio lacinia ut. Sed commodo porttitor turpis a pulvinar. Maecenas neque ipsum, pellentesque nec tincidunt et, malesuada sed enim. Vivamus pulvinar consequat ante, vel efficitur diam placerat et. Mauris vel leo a quam egestas tempor. Etiam a libero ipsum. Aenean sagittis ante in mi ornare, porta tincidunt libero sollicitudin. Proin mollis laoreet dolor, consectetur convallis massa blandit blandit. Etiam facilisis euismod tellus, ac pharetra lorem elementum vitae. In congue nunc vitae aliquet sollicitudin. Quisque rhoncus urna maximus tincidunt fringilla.
    Phasellus sollicitudin tincidunt vehicula. Phasellus eu elementum lectus. Suspendisse ut elit tempus, fermentum mi vel, sodales nisi. Nullam ac eleifend ex. In ac purus nec velit tincidunt iaculis. Nulla pretium ornare sapien. Praesent dignissim interdum eros, a tincidunt sem vestibulum a. Fusce posuere urna a ligula semper, ut vehicula diam fermentum.
    Maecenas non lacus tempus, tristique lorem vel, venenatis libero. Fusce id auctor ipsum, in accumsan nisl. Maecenas at mollis risus, ut pulvinar quam. Nam ultrices sodales sagittis. Suspendisse potenti. Nulla convallis aliquet tellus at consequat. Etiam convallis et lacus efficitur tincidunt. Praesent at mi ut sem convallis maximus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed convallis condimentum ipsum tempor mollis. Fusce non malesuada orci.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et sem congue, iaculis ante et, facilisis enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam quis nisi at est viverra sagittis. Nullam eget lacinia velit. Mauris sagittis urna ut leo sagittis commodo. Donec pellentesque porta urna sed fermentum. Curabitur pretium nisi metus, sit amet porttitor elit porttitor ac. In hac habitasse platea dictumst. Etiam tempor, sem quis placerat dapibus, nisl mi sodales sem, tempus ullamcorper eros ante nec odio.
    Morbi a convallis ligula. Nunc lacinia, felis at mattis placerat, est enim tincidunt nibh, nec tempor sem diam quis odio. Curabitur mattis, urna non tincidunt bibendum, eros justo iaculis sem, et fermentum metus sapien vel erat. Suspendisse dignissim neque eu leo suscipit accumsan. Praesent consectetur maximus fermentum. Nullam sollicitudin, nunc consectetur fermentum porttitor, turpis leo ullamcorper leo, a volutpat erat mi vel nibh. Proin a massa ac sapien facilisis aliquet. Pellentesque sodales nisl sit amet ultrices scelerisque. Mauris a mauris est. Aenean at consectetur lorem. Proin interdum rutrum erat vel imperdiet. Maecenas ullamcorper scelerisque volutpat. Fusce tincidunt tempus bibendum.
    Morbi mollis neque lorem, sit amet lacinia odio lacinia ut. Sed commodo porttitor turpis a pulvinar. Maecenas neque ipsum, pellentesque nec tincidunt et, malesuada sed enim. Vivamus pulvinar consequat ante, vel efficitur diam placerat et. Mauris vel leo a quam egestas tempor. Etiam a libero ipsum. Aenean sagittis ante in mi ornare, porta tincidunt libero sollicitudin. Proin mollis laoreet dolor, consectetur convallis massa blandit blandit. Etiam facilisis euismod tellus, ac pharetra lorem elementum vitae. In congue nunc vitae aliquet sollicitudin. Quisque rhoncus urna maximus tincidunt fringilla.
    Phasellus sollicitudin tincidunt vehicula. Phasellus eu elementum lectus. Suspendisse ut elit tempus, fermentum mi vel, sodales nisi. Nullam ac eleifend ex. In ac purus nec velit tincidunt iaculis. Nulla pretium ornare sapien. Praesent dignissim interdum eros, a tincidunt sem vestibulum a. Fusce posuere urna a ligula semper, ut vehicula diam fermentum.
    Maecenas non lacus tempus, tristique lorem vel, venenatis libero. Fusce id auctor ipsum, in accumsan nisl. Maecenas at mollis risus, ut pulvinar quam. Nam ultrices sodales sagittis. Suspendisse potenti. Nulla convallis aliquet tellus at consequat. Etiam convallis et lacus efficitur tincidunt. Praesent at mi ut sem convallis maximus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed convallis condimentum ipsum tempor mollis. Fusce non malesuada orci.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et sem congue, iaculis ante et, facilisis enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam quis nisi at est viverra sagittis. Nullam eget lacinia velit. Mauris sagittis urna ut leo sagittis commodo. Donec pellentesque porta urna sed fermentum. Curabitur pretium nisi metus, sit amet porttitor elit porttitor ac. In hac habitasse platea dictumst. Etiam tempor, sem quis placerat dapibus, nisl mi sodales sem, tempus ullamcorper eros ante nec odio.
    Morbi a convallis ligula. Nunc lacinia, felis at mattis placerat, est enim tincidunt nibh, nec tempor sem diam quis odio. Curabitur mattis, urna non tincidunt bibendum, eros justo iaculis sem, et fermentum metus sapien vel erat. Suspendisse dignissim neque eu leo suscipit accumsan. Praesent consectetur maximus fermentum. Nullam sollicitudin, nunc consectetur fermentum porttitor, turpis leo ullamcorper leo, a volutpat erat mi vel nibh. Proin a massa ac sapien facilisis aliquet. Pellentesque sodales nisl sit amet ultrices scelerisque. Mauris a mauris est. Aenean at consectetur lorem. Proin interdum rutrum erat vel imperdiet. Maecenas ullamcorper scelerisque volutpat. Fusce tincidunt tempus bibendum.
    Morbi mollis neque lorem, sit amet lacinia odio lacinia ut. Sed commodo porttitor turpis a pulvinar. Maecenas neque ipsum, pellentesque nec tincidunt et, malesuada sed enim. Vivamus pulvinar consequat ante, vel efficitur diam placerat et. Mauris vel leo a quam egestas tempor. Etiam a libero ipsum. Aenean sagittis ante in mi ornare, porta tincidunt libero sollicitudin. Proin mollis laoreet dolor, consectetur convallis massa blandit blandit. Etiam facilisis euismod tellus, ac pharetra lorem elementum vitae. In congue nunc vitae aliquet sollicitudin. Quisque rhoncus urna maximus tincidunt fringilla.
    Phasellus sollicitudin tincidunt vehicula. Phasellus eu elementum lectus. Suspendisse ut elit tempus, fermentum mi vel, sodales nisi. Nullam ac eleifend ex. In ac purus nec velit tincidunt iaculis. Nulla pretium ornare sapien. Praesent dignissim interdum eros, a tincidunt sem vestibulum a. Fusce posuere urna a ligula semper, ut vehicula diam fermentum.
    Maecenas non lacus tempus, tristique lorem vel, venenatis libero. Fusce id auctor ipsum, in accumsan nisl. Maecenas at mollis risus, ut pulvinar quam. Nam ultrices sodales sagittis. Suspendisse potenti. Nulla convallis aliquet tellus at consequat. Etiam convallis et lacus efficitur tincidunt. Praesent at mi ut sem convallis maximus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed convallis condimentum ipsum tempor mollis. Fusce non malesuada orci.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et sem congue, iaculis ante et, facilisis enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam quis nisi at est viverra sagittis. Nullam eget lacinia velit. Mauris sagittis urna ut leo sagittis commodo. Donec pellentesque porta urna sed fermentum. Curabitur pretium nisi metus, sit amet porttitor elit porttitor ac. In hac habitasse platea dictumst. Etiam tempor, sem quis placerat dapibus, nisl mi sodales sem, tempus ullamcorper eros ante nec odio.
    Morbi a convallis ligula. Nunc lacinia, felis at mattis placerat, est enim tincidunt nibh, nec tempor sem diam quis odio. Curabitur mattis, urna non tincidunt bibendum, eros justo iaculis sem, et fermentum metus sapien vel erat. Suspendisse dignissim neque eu leo suscipit accumsan. Praesent consectetur maximus fermentum. Nullam sollicitudin, nunc consectetur fermentum porttitor, turpis leo ullamcorper leo, a volutpat erat mi vel nibh. Proin a massa ac sapien facilisis aliquet. Pellentesque sodales nisl sit amet ultrices scelerisque. Mauris a mauris est. Aenean at consectetur lorem. Proin interdum rutrum erat vel imperdiet. Maecenas ullamcorper scelerisque volutpat. Fusce tincidunt tempus bibendum.
    Morbi mollis neque lorem, sit amet lacinia odio lacinia ut. Sed commodo porttitor turpis a pulvinar. Maecenas neque ipsum, pellentesque nec tincidunt et, malesuada sed enim. Vivamus pulvinar consequat ante, vel efficitur diam placerat et. Mauris vel leo a quam egestas tempor. Etiam a libero ipsum. Aenean sagittis ante in mi ornare, porta tincidunt libero sollicitudin. Proin mollis laoreet dolor, consectetur convallis massa blandit blandit. Etiam facilisis euismod tellus, ac pharetra lorem elementum vitae. In congue nunc vitae aliquet sollicitudin. Quisque rhoncus urna maximus tincidunt fringilla.
    Phasellus sollicitudin tincidunt vehicula. Phasellus eu elementum lectus. Suspendisse ut elit tempus, fermentum mi vel, sodales nisi. Nullam ac eleifend ex. In ac purus nec velit tincidunt iaculis. Nulla pretium ornare sapien. Praesent dignissim interdum eros, a tincidunt sem vestibulum a. Fusce posuere urna a ligula semper, ut vehicula diam fermentum.
    Maecenas non lacus tempus, tristique lorem vel, venenatis libero. Fusce id auctor ipsum, in accumsan nisl. Maecenas at mollis risus, ut pulvinar quam. Nam ultrices sodales sagittis. Suspendisse potenti. Nulla convallis aliquet tellus at consequat. Etiam convallis et lacus efficitur tincidunt. Praesent at mi ut sem convallis maximus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed convallis condimentum ipsum tempor mollis. Fusce non malesuada orci.
  </main>

  <!-- Footer -->
  <?php include_once("includes/footer.php"); ?>

  <!-- Scripts -->
  <script src="js/main.js"></script>
</body>

</html>